spring:
  application:
    name: Autoflex Inventory API

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/autoflex_database}
    username: ${SPRING_DATASOURCE_USERNAME:autoflex}
    password: ${SPRING_DATASOURCE_PASSWORD:autoflex}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

security:
  jwt:
    secret: ${JWT_SECRET:SIK8vUDXM3+0VulGxuWum04oCG2xlp/ATeMIzOnYm+SxsRdYJCEEB6BlmzSw5l1S}
    expirationMinutes: ${JWT_EXPIRATION_MINUTES:120}

app:
  cors:
    allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:5173}
