spring:
  application:
    name: Autoflex Inventory API
  datasource:
    url: jdbc:postgresql://autoflex-database:5432/autoflex-database
    username: autoflex
    password: autoflex
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

security:
  jwt:
    secret: "SIK8vUDXM3+0VulGxuWum04oCG2xlp/ATeMIzOnYm+SxsRdYJCEEB6BlmzSw5l1S"
    expirationMinutes: 120

app:
  cors:
    allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:5173}
